name: Sync with GitLab
on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Push changes to GitLab
        run: |
          git remote add gitlab https://Wojtek94@gitlab.com/Wojtek94/TrelloRESTAutomatedTestsBackend
          git push gitlab main
